---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../external/business-operations/kubernetes/flux/crds
  - ./cluster-apps.yaml
  - ./cluster-base-apps.yaml
  - ./cluster-secrets.yaml
  - ./config
  - ../../../external/business-operations/kubernetes/flux/repositories
  - ./vars
