---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../external/business-operations/kubernetes/base-apps/flux-bootstrap
  - ../../../external/business-operations/kubernetes/base-apps/kube-system/ns
  - ../../../external/business-operations/kubernetes/base-apps/kube-system/cilium
  - ../../../external/business-operations/kubernetes/base-apps/kube-system/snapshot-controller
  - ../../../external/business-operations/kubernetes/base-apps/network/ns
  - ../../../external/business-operations/kubernetes/base-apps/network/ingress-nginx
  - ./rook-ceph
