---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../external/business-operations/kubernetes/flux/config
patches:
  - target:
      kind: Kustomization
      name: cluster
    patch: |
      - op: replace
        path: /spec/path
        value: ./kubernetes/cluster-demo-multi-node/flux
