apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
type: Opaque
stringData:
    LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
    LLDAP_LDAP_USER_PASS: ${LLDAP_PASSWORD}
    LLDAP_USER_DN: ${LLDAP_USER_DN}
    LLDAP_SERVER_KEY_SEED: ${LLDAP_SERVER_KEY_SEED}
