apiVersion: v1
kind: Secret
metadata:
    name: secret-cluster-settings
    namespace: flux-system
type: Opaque
stringData:
    cert_manager_aws_access_key_id: ${CERT_MANAGER_AWS_ACCESS_KEY_ID}
    cert_manager_aws_hosted_zone_id: ${CERT_MANAGER_AWS_HOSTED_ZONE_ID}
    cnpg_backup_endpoint: ${CNPG_BACKUP_ENDPOINT}
    cnpg_restore_endpoint: ${CNPG_RESTORE_ENDPOINT}
