---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../external/business-operations/kubernetes/apps/security/lldap

patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      name: cluster-apps-lldap
    patch: |
      - op: replace
        path: /spec/path
        value: ./kubernetes/cluster-demo-multi-node/apps/security/lldap/app
