---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../external/business-operations/kubernetes/apps/cert-manager/ns
  - ../../../../external/business-operations/kubernetes/apps/cert-manager/cert-manager

patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      name: cluster-apps-cert-manager-certificates-restore
    patch: |
      - op: replace
        path: /spec/path
        value: ./kubernetes/cluster-demo-multi-node/apps/cert-manager/certificates
