apiVersion: v1
kind: Secret
metadata:
    name: secret-cluster-settings
    namespace: flux-system
type: Opaque
stringData:
    cert_manager_aws_access_key_id: TODO
    cert_manager_aws_hosted_zone_id: TODO
    cnpg_backup_endpoint: TODO
    cnpg_restore_endpoint: TODO
