all:
  hosts:
    demo-single-node:
      ansible_host: 192.0.2.10
    # Needed, so that "inventory_dir" is defined
    localhost:
      ansible_connection: local
  children:
    initial_controller:
      hosts:
        demo-single-node:
    controllers:
      hosts:
    workers:
      hosts:
    workers_to_join:
      hosts:
  vars:
    ansible_user: root
    artifacts_dir: "{{ inventory_dir }}/artifacts/demo-single-node"
    cluster_path: "{{ inventory_dir }}/../kubernetes/cluster-demo"
    nixos_flake: "{{ inventory_dir }}/.."
    rook_ceph_cluster_values_files:
      - "{{ business_operations_dir }}/kubernetes/base-apps/rook-ceph/rook-ceph/cluster/values.yaml"
      - "{{ business_operations_dir }}/kubernetes/base-apps/rook-ceph/rook-ceph/cluster/values-no-dashboards.yaml"
      - "{{ business_operations_dir }}/kubernetes/base-apps/rook-ceph/rook-ceph/cluster-single-node/values.yaml"
