all:
  hosts:
    demo-single-node:
      ansible_host: 192.0.2.10
    # Needed, so that "inventory_dir" is defined
    localhost:
      ansible_connection: local
  children:
    initial_controller:
      hosts:
        demo-single-node:
    controllers:
      hosts:
    workers:
      hosts:
    workers_to_join:
      hosts:
  vars:
    ansible_user: root
    artifacts_dir: "{{ inventory_dir }}/artifacts/demo-single-node"
    nixos_flake: "{{ inventory_dir }}/.."
    skip_rook_ceph: false
    cilium_helmrelease_path: "../external/business-operations/kubernetes/base-apps/kube-system/cilium/app/helmrelease.yaml"
    cilium_values_files:
      - "../external/business-operations/kubernetes/base-apps/kube-system/cilium/app/values.yaml"
      - "../external/business-operations/kubernetes/base-apps/kube-system/cilium/app/values-no-dashboards.yaml"
    openebs_helmrelease_path: "../external/business-operations/kubernetes/base-apps/openebs/openebs/app/helmrelease.yaml"
    openebs_values_files:
      - "../external/business-operations/kubernetes/base-apps/openebs/openebs/app/values.yaml"
    rook_ceph_operator_helmrelease_path: "../external/business-operations/kubernetes/base-apps/rook-ceph/rook-ceph/operator/helmrelease.yaml"
    rook_ceph_operator_values_files:
      - "../external/business-operations/kubernetes/base-apps/rook-ceph/rook-ceph/operator/values.yaml"
      - "../external/business-operations/kubernetes/base-apps/rook-ceph/rook-ceph/operator/values-no-dashboards.yaml"
    rook_ceph_cluster_helmrelease_path: "../external/business-operations/kubernetes/base-apps/rook-ceph/rook-ceph/cluster/helmrelease.yaml"
    rook_ceph_cluster_values_files:
      - "../external/business-operations/kubernetes/base-apps/rook-ceph/rook-ceph/cluster/values.yaml"
      - "../external/business-operations/kubernetes/base-apps/rook-ceph/rook-ceph/cluster/values-no-dashboards.yaml"
